Upgrade 0.27
ConsorciAOC-PRJ/decidim-module-trusted-ids pull request #21
Opened 2024-01-03 09:08 UTC by antopalidi

#### :tophat: What? Why?
Upgrade Decidim 0.27.5

#### :pushpin: Related Issues
- Fixes #20

2024-01-04 20:08 UTC, antopalidi commented
@microstudi This pull request is ready for review

2024-01-05 10:45 UTC, microstudi requested changes
Good job Anna,

I've left a couple of comments, please check it out.
Also, please update the README file of any reference for version 0.26 to version 0.27!

2024-01-05 10:45 UTC, microstudi commented on CHANGELOG.md
> +
```suggestion
- Adds compatibility with Decidim 0.27
```

2024-01-05 10:45 UTC, microstudi commented on app/services/decidim/via_oberta/api/request.rb
> +                            <ns2:codigoMunicipio>#{municipal_code}</ns2:codigoMunicipio>#{" "}
is this a mistake?

2024-01-05 10:57 UTC, antopalidi commented on app/services/decidim/via_oberta/api/request.rb
> +                            <ns2:codigoMunicipio>#{municipal_code}</ns2:codigoMunicipio>#{" "}
yes, there was a space, I removed it

2024-01-05 11:08 UTC, microstudi approved these changes
great job!

2024-01-05 11:08 UTC, merged